"""DOCX extraction — body-order walk, inline images, styles, tables."""

from __future__ import annotations

import pytest

from doc2md.extract import extract


@pytest.fixture
def docx_doc(docs, cfg):
    return extract(docs["docx"], cfg)


def test_title_from_core_properties(docx_doc):
    assert docx_doc.title == "Quarterly Memo"
    assert docx_doc.slug == "quarterly-memo"


def test_heading_styles_map_to_levels(docx_doc):
    levels = {b.text: b.level for b in docx_doc.blocks if b.kind == "heading"}
    assert levels["Overview"] == 1
    assert levels["Detail"] == 2


def test_outline_level_is_used_when_style_is_not_a_heading(docx_doc):
    """Localized Word builds carry no "Heading N" style name, only outlineLvl."""
    levels = {b.text: b.level for b in docx_doc.blocks if b.kind == "heading"}
    assert levels["Outline Level Heading"] == 3  # outlineLvl 2 -> level 3


def test_image_lands_between_the_surrounding_paragraphs(docx_doc):
    sequence = [
        ("image", b.image.id) if b.kind == "image" else (b.kind, b.text)
        for b in docx_doc.blocks
    ]
    kinds = [k for k, _ in sequence]
    texts = [t for _, t in sequence]
    index = kinds.index("image")

    assert "Opening paragraph before the chart." in texts[:index]
    assert "Paragraph after the chart." in texts[index + 1:]


def test_image_bytes_are_extracted(docx_doc):
    images = docx_doc.images
    assert len(images) == 1
    assert images[0].extracted
    assert images[0].ext == ".png"


def test_caption_styled_paragraph_is_absorbed_into_the_image(docx_doc):
    assert docx_doc.images[0].caption == "Figure 1. Quarterly chart."


def test_absorbed_caption_is_not_also_body_text(docx_doc):
    body = [b.text for b in docx_doc.blocks if b.kind == "text"]
    assert "Figure 1. Quarterly chart." not in body


def test_image_locator_uses_the_preceding_heading_index(docx_doc):
    assert docx_doc.images[0].id.endswith("-h01-img01")


def test_table_renders_as_markdown(docx_doc):
    tables = [b.text for b in docx_doc.blocks if b.kind == "table"]
    assert len(tables) == 1
    lines = tables[0].splitlines()
    assert lines[0] == "| Region | Total |"
    assert lines[1] == "| --- | --- |"
    assert lines[2] == "| North | 120 |"


def test_has_h1_reflects_a_level_one_heading(docx_doc):
    assert docx_doc.has_h1 is True


def test_corrupt_docx_raises_runtime_error(isolated_cwd, cfg):
    broken = isolated_cwd / "broken.docx"
    broken.write_bytes(b"not a zip")
    with pytest.raises(RuntimeError, match="could not open DOCX"):
        extract(broken, cfg)


def test_empty_docx_is_noted(isolated_cwd, cfg):
    import docx

    target = isolated_cwd / "empty.docx"
    docx.Document().save(str(target))
    result = extract(target, cfg)
    assert any("no readable content" in n for n in result.notes)


def test_autogenerated_picture_names_are_not_used_as_captions(isolated_cwd, docs, cfg):
    """Word names shapes "Picture 3"; that is noise, not a caption."""
    import docx

    target = isolated_cwd / "plain.docx"
    document = docx.Document()
    document.add_heading("Head", level=1)
    document.add_picture(str(docs["chart_png"]))
    document.save(str(target))

    result = extract(target, cfg)
    assert result.images[0].caption == ""
